// Generated by CoffeeScript 1.9.3

/*
  This contains all the core logic that bots follow, tweak these values to influence how well bots play and make them more realistic.

  Attributes is different attributes bots can have which influences how they play.
  Default values for attributes are:
    min: 0
    max: 1
    decimalPlaces: 2
  If the attribute differs from these specify that in the object
 */
var _, logic;

_ = require('lodash');

logic = {
  attributes: {
    aggression: {
      min: 0.3,
      max: 0.9
    },
    gemCollectChance: {},
    randomness: {},
    patience: {
      max: 0.8
    },
    upgradeTowerChance: {
      min: 0.2,
      max: 0.7
    }
  },
  maxTowerBuildAggressionOffset: 0.5,
  startMinTargetTowerValue: 200,
  minTargetTowerValuePerMin: 20,
  maxTargetTowerValuePerMin: 40,
  exponentialPercentageIncreaseInTargetsEachMinute: 0.1,
  towerBiasPercentPerGold: 0.0005,
  patienceTime: 3,
  patienceDecayRate: 0.5,
  getRandomAttributes: function() {
    var attrInfo, attrValues, attributes, data, name;
    attributes = _.clone(this.attributes);
    attrValues = {};
    for (name in attributes) {
      data = attributes[name];
      attrInfo = _.extend({
        min: 0,
        max: 1,
        decimalPlaces: 2
      }, data);
      attrValues[name] = this.calculateAttributeValue(attrInfo.min, attrInfo.max, attrInfo.decimalPlaces);
    }
    return attrValues;
  },
  calculateAttributeValue: function(min, max, decimalPlaces) {
    return parseFloat(((Math.random() * (max - min)) + min).toFixed(decimalPlaces));
  }
};

module.exports = logic;
