// Generated by CoffeeScript 1.9.3
var config;

config = {
  requestTimeout: 10000,
  logToConsole: true,
  pickRaceMinDelay: 5000,
  pickRaceMaxDelay: 30000,
  lockInMinDelay: 2000,
  lockInMaxDelay: 10000,
  reportLoadedMinDelay: 5000,
  reportLoadedMaxDelay: 15000,
  gameTickRate: 10,
  actions: {
    buildTower: 0,
    upgradeTower: 1,
    placeMinion: 2
  },
  messages: {
    gameBeginning: "gameBeginning",
    towerCreated: "towerCreated",
    gemDropped: "gemDropped",
    collectGem: "collectGem"
  }
};

module.exports = config;
