// Generated by CoffeeScript 1.9.3
var config, path;

path = require('path');

config = {
  cookieKey: "express.sid",
  cookieSecret: process.env.COOKIE_SECRET || "notsosecretcookie",
  logLevel: 'info',
  logToConsole: true,
  logDir: path.normalize(__dirname + '/../logs'),
  metricsPort: 9091,
  maxTickProcessTime: 105,
  tileSize: 32,
  mapWidth: 960,
  mapHeight: 640,
  disconnectedSecondsBeforeGameEnds: 15,
  waitForHostToConnectTime: 15,
  waitForAllToConnectTime: 30,
  timeBeforeStart: 90,
  requestTimeout: 5000,
  maxConnectRetries: 3,
  maxGameTimeInMinutes: 60,
  tickTime: 100,
  autoAddBots: true,
  addLag: false,
  addBotLag: false,
  enableDebugLog: false,
  msg: {
    game: {
      detailsChanged: "detailsChanged"
    }
  },
  player: {
    minimumPacketResendDelay: 5,
    maxTicksBehind: 20
  },
  experiencePerGame: 100,
  stormPointsPerGame: 100,
  eloWeightingFactor: 32
};

if (process.env.NODE_ENV !== "development") {
  config.logDir = path.normalize(__dirname + '/../logs');
}

module.exports = config;
