// Generated by CoffeeScript 1.9.3
var _, config, dbVersion, dev, name, netConfig, prod, speedDbVersion,
  hasProp = {}.hasOwnProperty;

_ = require('lodash');

dbVersion = "0-6-4";

speedDbVersion = "";

dev = {
  bot: {
    port: 20000,
    host: 'localhost'
  },
  db: {
    port: 28015,
    host: 'localhost',
    authKey: ''
  },
  frontend: {
    port: 8080,
    host: 'localhost'
  },
  gs: {
    port: 8082,
    host: 'localhost',
    externalHost: process.env.C9_HOSTNAME || process.env.HOSTNAME || 'ts.dev'
  },
  lobby: {
    port: 8081,
    host: process.env.C9_HOSTNAME || process.env.HOSTNAME || 'ts.dev'
  }
};

prod = {};

if (process.env.NODE_ENV === 'production') {
  netConfig = _.merge(dev, prod);
} else {
  netConfig = _.merge(dev);
}

for (name in netConfig) {
  if (!hasProp.call(netConfig, name)) continue;
  config = netConfig[name];
  netConfig[name].url = "http://" + config.host + ":" + config.port;
}

module.exports = netConfig;
