// Generated by CoffeeScript 1.9.3
var _, config, dbVersion, dev, name, netConfig, prod, speedDbVersion, HOSTNAME,
  hasProp = {}.hasOwnProperty;

_ = require('lodash');

dbVersion = "0-6-4";
speedDbVersion = "";
HOSTNAME = process.env.C9_HOSTNAME || process.env.HOSTNAME || 'ts.devel';

dev = {
  bot: {
    port: 20000,
    host: 'localhost'
  },
  db: {
    port: 28015,
    host: 'localhost',
    authKey: ''
  },
  frontend: {
    port: 8080,
    host: 'localhost'
  },
  gs: {
    port: 8082,
    host: 'localhost',
    externalHost: HOSTNAME
  },
  lobby: {
    port: 8081,
    host: HOSTNAME
  }
};

prod = {};

if (process.env.NODE_ENV === 'production') {
  netConfig = _.merge(dev, prod);
} else {
  netConfig = _.merge(dev);
}

for (name in netConfig) {
  if (!hasProp.call(netConfig, name)) continue;
  config = netConfig[name];
  netConfig[name].url = "http://" + config.host + ":" + config.port;
}

module.exports = netConfig;
